services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    environment:
      - SESSION_SECRET=mysupersecretkey
      - TZ=America/New_York
    tty: true
    stop_signal: SIGINT
    devices:
      - "/dev/serial/by-id/usb-1a86_USB_Single_Serial_58E3038088-if00:/dev/zwave"
    ports:
      - "8091:8091" # port for web interface
      - "8093:8093" # port for Z-Wave JS websocket server
    volumes:
      - ../../data/zwave-js-ui/:/usr/src/app/store
    restart: always
